package pnls.AddsMenu;

import pnls.Productos1;

import Clases_data.*;
import java.util.List;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import Clases.*;
import Interfaz.Inicio;
import Interfaz.nuevoStock;
import javax.swing.JDialog;
public class detalleProducto extends javax.swing.JPanel {

    /**
     * Creates new form detalleProducto
     */
    public detalleProducto() {
        initComponents();
        jlNombre.setText(Productos1.nombre);
        jtPrecio.setText(Productos1.precio);
        jtCosto.setText(Productos1.costo);
        jtCodigo.setText(Productos1.codigo);
        jtCantidad.setText(Productos1.cantidad);
        
        agregarComboCategorias();
        agregarComboProvedores();
        AutoCompleteDecorator.decorate(this.jcbCategoria);
        AutoCompleteDecorator.decorate(this.jcbProvedor);
        
        
    }
    private void agregarComboCategorias(){
        try{
            Conexion con = new Conexion("jdbc:mysql://localhost:3306/e-wod","root","");
            Categoria_producto_data cpd = new Categoria_producto_data(con);
            List<Categoria_producto> listA = cpd.obtenerCategorias_producto();
            for (int i = 0; i < listA.size(); i++){
                jcbCategoria.addItem(listA.get(i).getNombre());
            }
            
        }catch (Exception e){
          JOptionPane.showMessageDialog(null, "Ocurrio un error inesperado, vuelve a intentar");
        }
    }
    
    private void agregarComboProvedores(){
        try{
            Conexion con = new Conexion("jdbc:mysql://localhost:3306/e-wod","root","");
            Provedor_data cd = new Provedor_data(con);
            List<Provedor> listA = cd.obtenerProvedores();
            for (int i = 0; i < listA.size(); i++){
                jcbProvedor.addItem(listA.get(i).getNombre());
            }
            
        }catch (Exception e){
          JOptionPane.showMessageDialog(null, "Ocurrio un error inesperado, vuelve a intentar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMenu = new javax.swing.JPanel();
        form = new javax.swing.JPanel();
        jlNombre = new javax.swing.JLabel();
        jtPrecio = new javax.swing.JTextField();
        jtCosto = new javax.swing.JTextField();
        jtCodigo = new javax.swing.JTextField();
        comentario = new javax.swing.JScrollPane();
        jtaComentario = new javax.swing.JTextArea();
        jbEditar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jtCantidad = new javax.swing.JTextField();
        jbNuevo_stock = new javax.swing.JButton();
        tituloStock = new javax.swing.JLabel();
        jcbCategoria = new javax.swing.JComboBox<>();
        jcbProvedor = new javax.swing.JComboBox<>();
        jlNombreProducto = new javax.swing.JLabel();
        jlCategoria = new javax.swing.JLabel();
        jlPrecio = new javax.swing.JLabel();
        jlCosto = new javax.swing.JLabel();
        jlCodigo = new javax.swing.JLabel();
        jlProvedor = new javax.swing.JLabel();
        jlComentario = new javax.swing.JLabel();
        tituloAddMenu = new javax.swing.JLabel();

        addMenu.setBackground(new java.awt.Color(224, 30, 90));
        addMenu.setPreferredSize(new java.awt.Dimension(300, 680));
        addMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        form.setBackground(new java.awt.Color(14, 21, 30));

        jlNombre.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 18)); // NOI18N
        jlNombre.setForeground(new java.awt.Color(255, 255, 255));
        jlNombre.setText("Nombre ");

        jtPrecio.setEnabled(false);
        jtPrecio.setSelectionColor(new java.awt.Color(224, 30, 90));

        jtCosto.setEnabled(false);
        jtCosto.setSelectionColor(new java.awt.Color(224, 30, 90));

        jtCodigo.setEnabled(false);
        jtCodigo.setSelectionColor(new java.awt.Color(224, 30, 90));

        jtaComentario.setColumns(20);
        jtaComentario.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtaComentario.setLineWrap(true);
        jtaComentario.setRows(5);
        jtaComentario.setEnabled(false);
        jtaComentario.setSelectionColor(new java.awt.Color(224, 30, 90));
        comentario.setViewportView(jtaComentario);

        jbEditar.setBackground(new java.awt.Color(224, 30, 90));
        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets.Icons/Editar.png"))); // NOI18N
        jbEditar.setBorderPainted(false);
        jbEditar.setPreferredSize(new java.awt.Dimension(30, 30));
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbBorrar.setBackground(new java.awt.Color(224, 30, 90));
        jbBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets.Icons/borrar.png"))); // NOI18N
        jbBorrar.setBorderPainted(false);
        jbBorrar.setPreferredSize(new java.awt.Dimension(30, 30));
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jtCantidad.setEditable(false);
        jtCantidad.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtCantidad.setText("10u");
        jtCantidad.setPreferredSize(new java.awt.Dimension(80, 30));
        jtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCantidadActionPerformed(evt);
            }
        });

        jbNuevo_stock.setBackground(new java.awt.Color(224, 30, 90));
        jbNuevo_stock.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 14)); // NOI18N
        jbNuevo_stock.setForeground(new java.awt.Color(255, 255, 255));
        jbNuevo_stock.setText("Nuevo Stock");
        jbNuevo_stock.setBorderPainted(false);
        jbNuevo_stock.setPreferredSize(new java.awt.Dimension(240, 35));
        jbNuevo_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevo_stockActionPerformed(evt);
            }
        });

        tituloStock.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tituloStock.setForeground(new java.awt.Color(255, 255, 255));
        tituloStock.setText("Cantidad Stock");

        jcbCategoria.setEditable(true);
        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jcbCategoria.setEnabled(false);

        jcbProvedor.setEditable(true);
        jcbProvedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jcbProvedor.setEnabled(false);

        jlNombreProducto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlNombreProducto.setForeground(new java.awt.Color(255, 255, 255));
        jlNombreProducto.setText("Nombre del Producto");

        jlCategoria.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jlCategoria.setText("Categoria");

        jlPrecio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jlPrecio.setText("Precio");

        jlCosto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlCosto.setForeground(new java.awt.Color(255, 255, 255));
        jlCosto.setText("Costo");

        jlCodigo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jlCodigo.setText("Codigo");

        jlProvedor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlProvedor.setForeground(new java.awt.Color(255, 255, 255));
        jlProvedor.setText("Proveedor");

        jlComentario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlComentario.setForeground(new java.awt.Color(255, 255, 255));
        jlComentario.setText("Comentario");

        javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
        form.setLayout(formLayout);
        formLayout.setHorizontalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(comentario)
                        .addComponent(jbNuevo_stock, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                            .addComponent(tituloStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(jtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlProvedor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                            .addComponent(jlNombreProducto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                            .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
                            .addComponent(jlNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jtCosto)
                        .addComponent(jtPrecio)
                        .addComponent(jcbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbProvedor, 0, 240, Short.MAX_VALUE)
                        .addComponent(jtCodigo)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        formLayout.setVerticalGroup(
            formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNombreProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCategoria)
                .addGap(7, 7, 7)
                .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlCosto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jlCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlProvedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbProvedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jlComentario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comentario, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloStock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbNuevo_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        addMenu.add(form, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        tituloAddMenu.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 14)); // NOI18N
        tituloAddMenu.setForeground(new java.awt.Color(255, 255, 255));
        tituloAddMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloAddMenu.setText("Detalles del Producto");
        tituloAddMenu.setPreferredSize(new java.awt.Dimension(300, 30));
        addMenu.add(tituloAddMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCantidadActionPerformed

        
    }//GEN-LAST:event_jtCantidadActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        if (!jtPrecio.isEnabled()){
            jtPrecio.setEnabled(true);
            jtCosto.setEnabled(true);
            jtCodigo.setEnabled(true);
            jtaComentario.setEnabled(true);
            jcbCategoria.setEnabled(true);
            jcbProvedor.setEnabled(true);
        } else {
            int msj = JOptionPane.showConfirmDialog(null,"¿Estas seguro de querer editar este cliente?");
            if(JOptionPane.YES_OPTION == msj){
                try{
                    Conexion con = new Conexion("jdbc:mysql://localhost:3306/e-wod","root","");
                    Producto_data cd = new Producto_data(con);
                    Provedor_data pd = new Provedor_data(con);
                    Categoria_producto_data cpd = new Categoria_producto_data(con);
                    int indice = jcbCategoria.getSelectedIndex();
                    int indice2 = jcbProvedor.getSelectedIndex();
                    int id_categoria =  cpd.getCategoria_por_nombre(this.jcbCategoria.getItemAt(indice)).getId();
                    int id_provedor = pd.getProvedor_por_nombre(this.jcbProvedor.getItemAt(indice2)).getId();

                    Producto producto = new Producto(jlNombre.getText(), id_categoria, Double.parseDouble(jtCosto.getText()), Double.parseDouble(jtPrecio.getText()), Integer.parseInt(jtCantidad.getText()), id_provedor, jtaComentario.getText(), Integer.parseInt(jtCodigo.getText()));

                    cd.actualizarProducto_por_id(producto, Productos1.producto_pasado.getId());

                    JOptionPane.showMessageDialog(null, "Se actualizo con exito el Producto" );

                    this.setVisible(false);
                    Productos1.addMenu.add(Productos1.jlBackground);

                } catch (Exception e){
                    JOptionPane.showMessageDialog(null, "No se pudo actualizar el producto, quedaron campos sin rellenar o intente nuevamente ");
                }
            }
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        int msj = JOptionPane.showConfirmDialog(null,"¿Estas seguro de querer borrar este producto?");
        if(JOptionPane.YES_OPTION == msj){
            try{
                Conexion con = new Conexion("jdbc:mysql://localhost:3306/e-wod","root","");
                Producto_data producto_data = new Producto_data(con);
                producto_data.borrarProducto(Productos1.producto_pasado);

                JOptionPane.showMessageDialog(null, "Se borro con exito el producto" );

                this.setVisible(false);
                Productos1.addMenu.add(Productos1.jlBackground);

            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "No se pudo borrar el producto, intente nuevamente ");
            }
        }
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbNuevo_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevo_stockActionPerformed
        Inicio.jlFondo.setVisible(true);
        JDialog a = new nuevoStock(null,true);
        a.setVisible(true);
    }//GEN-LAST:event_jbNuevo_stockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addMenu;
    private javax.swing.JScrollPane comentario;
    private javax.swing.JPanel form;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbNuevo_stock;
    private javax.swing.JComboBox<String> jcbCategoria;
    private javax.swing.JComboBox<String> jcbProvedor;
    private javax.swing.JLabel jlCategoria;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlComentario;
    private javax.swing.JLabel jlCosto;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNombreProducto;
    private javax.swing.JLabel jlPrecio;
    private javax.swing.JLabel jlProvedor;
    public static javax.swing.JTextField jtCantidad;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtCosto;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextArea jtaComentario;
    private javax.swing.JLabel tituloAddMenu;
    private javax.swing.JLabel tituloStock;
    // End of variables declaration//GEN-END:variables
}
