/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pnls.AddsMenu;


import Clases.Cliente;
import Clases.Conexion;
import Clases_data.Cliente_data;
import Interfaz.Inicio;
import Interfaz.nuevaTransaccion;
import java.awt.Color;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import pnls.Clientes1;
public class detalleCliente extends javax.swing.JPanel {

    /**
     * Creates new form asdTest
     */
    public detalleCliente() {
        initComponents();
        try{
            jlNombre.setText(Clientes1.nombre);
            jtBox.setText(Clientes1.box);
            jtTelefono.setText(Clientes1.telefono);
            jtEmail.setText(Clientes1.email);
            jtMetodo_de_pago.setText(Clientes1.cliente_pasado.getMetodo_de_pago_preferido());
            jlSaldo.setText(Clientes1.saldo);
            if (Double.parseDouble(jlSaldo.getText()) < 0){
                jlSaldo.setForeground(Color.red);
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error desconocido " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMenu = new javax.swing.JPanel();
        form = new javax.swing.JPanel();
        jlNombre = new javax.swing.JLabel();
        jbEditar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jlSaldo = new javax.swing.JTextField();
        jbTransaccion = new javax.swing.JButton();
        tituloCuentacorriente = new javax.swing.JLabel();
        jlBox = new javax.swing.JLabel();
        jlTelefono = new javax.swing.JLabel();
        jtTelefono = new javax.swing.JTextField();
        jlEmail = new javax.swing.JLabel();
        jtEmail = new javax.swing.JTextField();
        jlMetodo = new javax.swing.JLabel();
        jtMetodo_de_pago = new javax.swing.JTextField();
        jlComentario = new javax.swing.JLabel();
        jspComentario = new javax.swing.JScrollPane();
        jtaComentario = new javax.swing.JTextArea();
        jlNombreyApellido = new javax.swing.JLabel();
        jtBox = new javax.swing.JTextField();
        tituloAddMenu = new javax.swing.JLabel();

        addMenu.setBackground(new java.awt.Color(54, 197, 240));
        addMenu.setPreferredSize(new java.awt.Dimension(300, 680));
        addMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        form.setBackground(new java.awt.Color(14, 21, 30));
        form.setPreferredSize(new java.awt.Dimension(300, 650));
        form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlNombre.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 18)); // NOI18N
        jlNombre.setForeground(new java.awt.Color(255, 255, 255));
        jlNombre.setText("Nombre Apellido");
        jlNombre.setPreferredSize(new java.awt.Dimension(200, 30));
        form.add(jlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 47, -1, -1));

        jbEditar.setBackground(new java.awt.Color(54, 197, 240));
        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets.Icons/Editar.png"))); // NOI18N
        jbEditar.setBorderPainted(false);
        jbEditar.setPreferredSize(new java.awt.Dimension(30, 30));
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });
        form.add(jbEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 11, -1, -1));

        jbBorrar.setBackground(new java.awt.Color(54, 197, 240));
        jbBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets.Icons/borrar.png"))); // NOI18N
        jbBorrar.setBorderPainted(false);
        jbBorrar.setPreferredSize(new java.awt.Dimension(30, 30));
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });
        form.add(jbBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 49, -1, -1));

        jlSaldo.setEditable(false);
        jlSaldo.setBackground(new java.awt.Color(255, 255, 255));
        jlSaldo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jlSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jlSaldo.setText("0,00");
        jlSaldo.setPreferredSize(new java.awt.Dimension(80, 30));
        jlSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlSaldoActionPerformed(evt);
            }
        });
        form.add(jlSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 438, -1, -1));

        jbTransaccion.setBackground(new java.awt.Color(54, 197, 240));
        jbTransaccion.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 14)); // NOI18N
        jbTransaccion.setForeground(new java.awt.Color(255, 255, 255));
        jbTransaccion.setText("Nueva transacción");
        jbTransaccion.setBorderPainted(false);
        jbTransaccion.setPreferredSize(new java.awt.Dimension(240, 35));
        jbTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTransaccionActionPerformed(evt);
            }
        });
        form.add(jbTransaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 486, -1, -1));

        tituloCuentacorriente.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tituloCuentacorriente.setForeground(new java.awt.Color(255, 255, 255));
        tituloCuentacorriente.setText("Cuenta Corriente");
        form.add(tituloCuentacorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 437, -1, 30));

        jlBox.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlBox.setForeground(new java.awt.Color(255, 255, 255));
        jlBox.setText("Box");
        form.add(jlBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 97, 64, -1));

        jlTelefono.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jlTelefono.setText("Telefono");
        form.add(jlTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 160, 64, -1));

        jtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtTelefonoFocusLost(evt);
            }
        });
        jtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTelefonoActionPerformed(evt);
            }
        });
        jtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtTelefonoKeyTyped(evt);
            }
        });
        form.add(jtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 181, 240, 30));

        jlEmail.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlEmail.setForeground(new java.awt.Color(255, 255, 255));
        jlEmail.setText("E-mail");
        form.add(jlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 217, 64, -1));

        jtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtEmailFocusLost(evt);
            }
        });
        form.add(jtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 238, 240, 30));

        jlMetodo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlMetodo.setForeground(new java.awt.Color(255, 255, 255));
        jlMetodo.setText("Metodo de pago preferido");
        form.add(jlMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 275, 205, -1));

        jtMetodo_de_pago.setPreferredSize(new java.awt.Dimension(125, 30));
        jtMetodo_de_pago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtMetodo_de_pagoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtMetodo_de_pagoFocusLost(evt);
            }
        });
        jtMetodo_de_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMetodo_de_pagoActionPerformed(evt);
            }
        });
        jtMetodo_de_pago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtMetodo_de_pagoKeyTyped(evt);
            }
        });
        form.add(jtMetodo_de_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 296, 240, -1));

        jlComentario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlComentario.setForeground(new java.awt.Color(255, 255, 255));
        jlComentario.setText("Comentario");
        form.add(jlComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 332, 99, -1));

        jtaComentario.setColumns(20);
        jtaComentario.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtaComentario.setLineWrap(true);
        jtaComentario.setRows(5);
        jtaComentario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtaComentarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtaComentarioFocusLost(evt);
            }
        });
        jspComentario.setViewportView(jtaComentario);

        form.add(jspComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 353, 240, 66));

        jlNombreyApellido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlNombreyApellido.setForeground(new java.awt.Color(255, 255, 255));
        jlNombreyApellido.setText("Nombre y Apellido");
        form.add(jlNombreyApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 117, -1));

        jtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBoxActionPerformed(evt);
            }
        });
        form.add(jtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 240, 30));

        addMenu.add(form, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        tituloAddMenu.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 14)); // NOI18N
        tituloAddMenu.setForeground(new java.awt.Color(255, 255, 255));
        tituloAddMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloAddMenu.setText("Perfil de Cliente");
        tituloAddMenu.setPreferredSize(new java.awt.Dimension(300, 30));
        addMenu.add(tituloAddMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        int msj = JOptionPane.showConfirmDialog(null,"¿Estas seguro de querer editar este cliente?");
        if(JOptionPane.YES_OPTION == msj){
            try{
                Conexion con = new Conexion("jdbc:mysql://localhost:3306/e-wod","root","");
                Cliente_data cd = new Cliente_data(con);
                Cliente cliente = new Cliente(jlNombre.getText(), Long.parseLong(jtTelefono.getText()), jtEmail.getText(), jtBox.getText(), jtMetodo_de_pago.getText(), jtaComentario.getText());

                cd.actualizarCliente_por_id(cliente, Clientes1.cliente_pasado.getId());

                JOptionPane.showMessageDialog(null, "Se actualizo con exito el Cliente" );

                this.setVisible(false);
                Clientes1.addMenu.add(Clientes1.jlBackground);

            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "No se pudo cargar la tabla " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        int msj = JOptionPane.showConfirmDialog(null,"¿Estas seguro de querer borrar este cliente?");
        if(JOptionPane.YES_OPTION == msj){
            try{
                Conexion con = new Conexion("jdbc:mysql://localhost:3306/e-wod","root","");
                Cliente_data cd = new Cliente_data(con);
                cd.borrarCliente(Clientes1.cliente_pasado);

                JOptionPane.showMessageDialog(null, "Se borro con exito el Cliente" );

                this.setVisible(false);
                Clientes1.addMenu.add(Clientes1.jlBackground);

            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "No se pudo cargar la tabla ");
            }
        }
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jlSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlSaldoActionPerformed

    private void jbTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTransaccionActionPerformed
        Inicio.jlFondo.setVisible(true);
        JDialog a = new nuevaTransaccion(null,true);
        a.setVisible(true);
    }//GEN-LAST:event_jbTransaccionActionPerformed

    private void jtTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtTelefonoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTelefonoFocusGained

    private void jtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtTelefonoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTelefonoFocusLost

    private void jtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTelefonoActionPerformed

    private void jtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTelefonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTelefonoKeyTyped

    private void jtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtEmailFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmailFocusGained

    private void jtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtEmailFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmailFocusLost

    private void jtMetodo_de_pagoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtMetodo_de_pagoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMetodo_de_pagoFocusGained

    private void jtMetodo_de_pagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtMetodo_de_pagoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMetodo_de_pagoFocusLost

    private void jtMetodo_de_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMetodo_de_pagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMetodo_de_pagoActionPerformed

    private void jtMetodo_de_pagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtMetodo_de_pagoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMetodo_de_pagoKeyTyped

    private void jtaComentarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtaComentarioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtaComentarioFocusGained

    private void jtaComentarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtaComentarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtaComentarioFocusLost

    private void jtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addMenu;
    private javax.swing.JPanel form;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbTransaccion;
    private javax.swing.JLabel jlBox;
    private javax.swing.JLabel jlComentario;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlMetodo;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNombreyApellido;
    private javax.swing.JTextField jlSaldo;
    private javax.swing.JLabel jlTelefono;
    private javax.swing.JScrollPane jspComentario;
    private javax.swing.JTextField jtBox;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtMetodo_de_pago;
    private javax.swing.JTextField jtTelefono;
    private javax.swing.JTextArea jtaComentario;
    private javax.swing.JLabel tituloAddMenu;
    private javax.swing.JLabel tituloCuentacorriente;
    // End of variables declaration//GEN-END:variables
}
