/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pnls.AddsMenu;

import Clases_data.*;
import java.awt.Color;
import javax.swing.JOptionPane;
import Clases.*;
import javax.swing.JTextField;
import pnls.Gastos1;
public class nuevaCatGasto extends javax.swing.JPanel {

    /**
     * Creates new form nuevaCatGasto
     */
    public nuevaCatGasto() {
        initComponents();
    }
    public boolean Campo_valido(JTextField campo){
        if (campo.getText().length() > 0 && !campo.getText().equals("Es necesario rellenar este campo")){
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMenu = new javax.swing.JPanel();
        form = new javax.swing.JPanel();
        Comentario = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jtConfirmar = new javax.swing.JButton();
        jtNombre = new javax.swing.JTextField();
        jlNombre = new javax.swing.JLabel();
        jlComentario = new javax.swing.JLabel();
        tituloAddMenu = new javax.swing.JLabel();

        addMenu.setBackground(new java.awt.Color(46, 182, 125));
        addMenu.setPreferredSize(new java.awt.Dimension(300, 680));
        addMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        form.setBackground(new java.awt.Color(14, 21, 30));
        form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        Comentario.setViewportView(jTextArea1);

        form.add(Comentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 117, 240, 66));

        jtConfirmar.setBackground(new java.awt.Color(46, 182, 125));
        jtConfirmar.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 14)); // NOI18N
        jtConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        jtConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets.Icons/confirmar.png"))); // NOI18N
        jtConfirmar.setText("Confirmar");
        jtConfirmar.setBorderPainted(false);
        jtConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtConfirmarActionPerformed(evt);
            }
        });
        form.add(jtConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 201, 240, 32));

        jtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNombreFocusLost(evt);
            }
        });
        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });
        form.add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 48, 240, 30));

        jlNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlNombre.setForeground(new java.awt.Color(255, 255, 255));
        jlNombre.setText("Nombre de la Categoria");
        form.add(jlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 150, -1));

        jlComentario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlComentario.setForeground(new java.awt.Color(255, 255, 255));
        jlComentario.setText("Comentario");
        form.add(jlComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 97, 117, -1));

        addMenu.add(form, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 650));

        tituloAddMenu.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 14)); // NOI18N
        tituloAddMenu.setForeground(new java.awt.Color(255, 255, 255));
        tituloAddMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloAddMenu.setText("Nueva Categoria");
        tituloAddMenu.setPreferredSize(new java.awt.Dimension(300, 30));
        addMenu.add(tituloAddMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreActionPerformed

    private void jtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNombreFocusGained
        this.jtNombre.setText("");
        jtNombre.setForeground(Color.black);
    }//GEN-LAST:event_jtNombreFocusGained

    private void jtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNombreFocusLost
        if("".equals(jtNombre.getText())){
            jtNombre.setForeground(Color.red);
            jtNombre.setText("Es necesario rellenar este campo");
        }
    }//GEN-LAST:event_jtNombreFocusLost

    private void jtConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtConfirmarActionPerformed
        int msj = JOptionPane.showConfirmDialog(null,"¿Estas seguro de querer agregar esta categoria?");
        if(JOptionPane.YES_OPTION == msj){
            try {
                if (Campo_valido(this.jtNombre)){
                    
                    Conexion con = null;
                    con = new Conexion("jdbc:mysql://localhost:3306/e-wod","root","");
                    Categoria_data cpd = new Categoria_data(con);
                    Categoria categoria;
                    categoria = new Categoria(jtNombre.getText());
                    
                    cpd.guardarCategoria(categoria);
                    
                    JOptionPane.showMessageDialog(null, "Felicidades, categoria agregado");

                    this.setVisible(false);
                    Gastos1.addMenu.add(Gastos1.jlBackground);

                    con.close();
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Ocurrio un error al guardar la categoria, un campo quedo sin rellenar");
                }
            } catch (Exception e){
                System.out.println("Error al instanciar la clase conexion" + e.getMessage());
                JOptionPane.showMessageDialog(null,"No se pudo guardar la categoria, intente nuevamente " + e);
            }
        }
    }//GEN-LAST:event_jtConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Comentario;
    private javax.swing.JPanel addMenu;
    private javax.swing.JPanel form;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlComentario;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JButton jtConfirmar;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JLabel tituloAddMenu;
    // End of variables declaration//GEN-END:variables
}
