/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pnls;

/**
 *
 * @author Alex
 */
public class Ajustes extends javax.swing.JPanel {

    /**
     * Creates new form Ajustes
     */
    public Ajustes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcbBuscar = new RSMaterialComponent.RSComboBoxMaterial();
        jpAjustesList = new javax.swing.JPanel();
        jpTitulo1 = new javax.swing.JPanel();
        jlTituloDesde3 = new javax.swing.JLabel();
        jlDesconectado1 = new javax.swing.JLabel();
        jlConectado1 = new javax.swing.JLabel();
        jbCargar = new newscomponents.RSButtonFlat_new();
        jSeparator1 = new javax.swing.JSeparator();
        jlTituloBaseCargada = new javax.swing.JLabel();
        jlNombreArchivo1 = new javax.swing.JLabel();
        jpTitulo2 = new javax.swing.JPanel();
        jlTituloDesde6 = new javax.swing.JLabel();
        jlTituloContacto = new javax.swing.JLabel();
        jlContacto = new javax.swing.JLabel();
        jpTitulo3 = new javax.swing.JPanel();
        jlTituloDesde1 = new javax.swing.JLabel();
        jlTituloVersion = new javax.swing.JLabel();
        jlVersion = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1466, 839));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setPreferredSize(new java.awt.Dimension(1466, 120));

        jLabel5.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 50)); // NOI18N
        jLabel5.setText("Ajustes");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets.Title/AjustesR.png"))); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(50, 50));

        jcbBuscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buscar en Ajustes", "Modo Oscuro", "Base de Datos", "Mantenimiento", "Version del Cliente" }));
        jcbBuscar.setColorMaterial(new java.awt.Color(236, 178, 46));
        jcbBuscar.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 14)); // NOI18N
        jcbBuscar.setPreferredSize(new java.awt.Dimension(250, 35));
        jcbBuscar.setThemeTooltip(necesario.Global.THEMETOOLTIP.LIGHT);

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGroup(TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TituloLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TituloLayout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jcbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(386, Short.MAX_VALUE))
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jpAjustesList.setBackground(new java.awt.Color(255, 255, 255));
        jpAjustesList.setPreferredSize(new java.awt.Dimension(720, 680));
        jpAjustesList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo1.setBackground(new java.awt.Color(14, 21, 30));
        jpTitulo1.setPreferredSize(new java.awt.Dimension(710, 50));
        jpTitulo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTituloDesde3.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 18)); // NOI18N
        jlTituloDesde3.setForeground(new java.awt.Color(255, 255, 255));
        jlTituloDesde3.setText("Base de Datos");
        jlTituloDesde3.setPreferredSize(new java.awt.Dimension(150, 35));
        jpTitulo1.add(jlTituloDesde3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 140, 30));

        jlDesconectado1.setBackground(new java.awt.Color(204, 204, 204));
        jlDesconectado1.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 14)); // NOI18N
        jlDesconectado1.setForeground(new java.awt.Color(255, 255, 255));
        jlDesconectado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlDesconectado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets.Icons/backup1.png"))); // NOI18N
        jlDesconectado1.setText("Desconectado");
        jlDesconectado1.setIconTextGap(10);
        jlDesconectado1.setOpaque(true);
        jlDesconectado1.setPreferredSize(new java.awt.Dimension(150, 35));
        jpTitulo1.add(jlDesconectado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 150, 50));

        jlConectado1.setBackground(new java.awt.Color(46, 182, 125));
        jlConectado1.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 14)); // NOI18N
        jlConectado1.setForeground(new java.awt.Color(255, 255, 255));
        jlConectado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlConectado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets.Icons/backup0.png"))); // NOI18N
        jlConectado1.setText("Conectado");
        jlConectado1.setIconTextGap(10);
        jlConectado1.setOpaque(true);
        jlConectado1.setPreferredSize(new java.awt.Dimension(150, 35));
        jpTitulo1.add(jlConectado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 150, 50));

        jpAjustesList.add(jpTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        jbCargar.setBackground(new java.awt.Color(14, 21, 30));
        jbCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets.Icons/backup2.png"))); // NOI18N
        jbCargar.setText("Cargar Archivo");
        jbCargar.setFont(new java.awt.Font("Metropolis Semi Bold", 1, 14)); // NOI18N
        jbCargar.setIconTextGap(10);
        jbCargar.setPreferredSize(new java.awt.Dimension(160, 35));
        jbCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCargarActionPerformed(evt);
            }
        });
        jpAjustesList.add(jbCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 180, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(5, 43));
        jpAjustesList.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 76, 10, -1));

        jlTituloBaseCargada.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 14)); // NOI18N
        jlTituloBaseCargada.setText("Base de datos cargada:");
        jlTituloBaseCargada.setPreferredSize(new java.awt.Dimension(150, 35));
        jpAjustesList.add(jlTituloBaseCargada, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 170, 30));

        jlNombreArchivo1.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 13)); // NOI18N
        jlNombreArchivo1.setForeground(new java.awt.Color(153, 153, 153));
        jlNombreArchivo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNombreArchivo1.setText("Nombre del Archivo");
        jlNombreArchivo1.setPreferredSize(new java.awt.Dimension(150, 35));
        jpAjustesList.add(jlNombreArchivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 180, 30));

        jpTitulo2.setBackground(new java.awt.Color(14, 21, 30));
        jpTitulo2.setPreferredSize(new java.awt.Dimension(710, 50));
        jpTitulo2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTituloDesde6.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 18)); // NOI18N
        jlTituloDesde6.setForeground(new java.awt.Color(255, 255, 255));
        jlTituloDesde6.setText("Mantenimiento");
        jlTituloDesde6.setPreferredSize(new java.awt.Dimension(150, 35));
        jpTitulo2.add(jlTituloDesde6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 190, 30));

        jpAjustesList.add(jpTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 710, -1));

        jlTituloContacto.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 14)); // NOI18N
        jlTituloContacto.setText("Contacto:");
        jlTituloContacto.setPreferredSize(new java.awt.Dimension(150, 35));
        jpAjustesList.add(jlTituloContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 170, 30));

        jlContacto.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 13)); // NOI18N
        jlContacto.setForeground(new java.awt.Color(153, 153, 153));
        jlContacto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlContacto.setText("switch.info2@gmail.com");
        jlContacto.setPreferredSize(new java.awt.Dimension(150, 35));
        jpAjustesList.add(jlContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 280, 30));

        jpTitulo3.setBackground(new java.awt.Color(14, 21, 30));
        jpTitulo3.setPreferredSize(new java.awt.Dimension(710, 50));
        jpTitulo3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTituloDesde1.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 18)); // NOI18N
        jlTituloDesde1.setForeground(new java.awt.Color(255, 255, 255));
        jlTituloDesde1.setText("Versión del cliente");
        jlTituloDesde1.setPreferredSize(new java.awt.Dimension(150, 35));
        jpTitulo3.add(jlTituloDesde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 190, 30));

        jpAjustesList.add(jpTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 710, -1));

        jlTituloVersion.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 14)); // NOI18N
        jlTituloVersion.setText("Versión del cliente:");
        jlTituloVersion.setPreferredSize(new java.awt.Dimension(150, 35));
        jpAjustesList.add(jlTituloVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 170, 30));

        jlVersion.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 13)); // NOI18N
        jlVersion.setForeground(new java.awt.Color(153, 153, 153));
        jlVersion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlVersion.setText("vBeta - B0.98");
        jlVersion.setPreferredSize(new java.awt.Dimension(150, 35));
        jpAjustesList.add(jlVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 280, 30));

        jPanel1.add(jpAjustesList, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 140, 710, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1462, 818));
    }// </editor-fold>//GEN-END:initComponents

    private void jbCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCargarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Titulo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private newscomponents.RSButtonFlat_new jbCargar;
    private RSMaterialComponent.RSComboBoxMaterial jcbBuscar;
    private javax.swing.JLabel jlConectado1;
    private javax.swing.JLabel jlContacto;
    private javax.swing.JLabel jlDesconectado1;
    private javax.swing.JLabel jlNombreArchivo1;
    private javax.swing.JLabel jlTituloBaseCargada;
    private javax.swing.JLabel jlTituloContacto;
    private javax.swing.JLabel jlTituloDesde1;
    private javax.swing.JLabel jlTituloDesde3;
    private javax.swing.JLabel jlTituloDesde6;
    private javax.swing.JLabel jlTituloVersion;
    private javax.swing.JLabel jlVersion;
    private javax.swing.JPanel jpAjustesList;
    private javax.swing.JPanel jpTitulo1;
    private javax.swing.JPanel jpTitulo2;
    private javax.swing.JPanel jpTitulo3;
    // End of variables declaration//GEN-END:variables
}
