/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pnls;

import Clases.*;
import Clases_data.*;
import java.util.List;
import javax.swing.JOptionPane;
import pnls.AddsMenu.detalleProvedor;
import pnls.AddsMenu.nuevoProvedor;
public class Provedores1 extends javax.swing.JPanel {

    /**
     * Creates new form Provedores
     */
    public Provedores1() {
        initComponents();try{
            Conexion con = new Conexion("jdbc:mysql://localhost:3306/e-wod","root","");
            Provedor_data provedor_data = new Provedor_data(con);
            List<Provedor> lista_provedores = provedor_data.obtenerProvedores();
            
            mostrarLista(lista_provedores);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "No se pudo cargar la tabla, inicie el xampp " );
        }
        
    }
    
    public void mostrarLista(List<Provedor> lista){
        try{
            String matris[][] = new String[lista.size()][4];
            
            for (int i = 0; i < lista.size(); i++){
                matris[i][0] = lista.get(i).getNombre();
                matris[i][1] = lista.get(i).getDireccion();
                matris[i][2] = Long.toString(lista.get(i).getTelefono());
                matris[i][3] = lista.get(i).getCorreo();
            }
            
            jtProvedores.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Nombre", "Direccion", "Numero", "E-Mail"
            }
        ) {
        });
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ocurrio un error inesperado en la lista, vuelve a intentarlo");
        
        }
    }
    public static String nombre, direccion, telefono, correo;
    public static Provedor provedor_pasado;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbNuevoProvedor = new rsbuttoncustom.RSButtonCustom();
        addMenu = new javax.swing.JPanel();
        jlBackground = new javax.swing.JLabel();
        Registro = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtProvedores = new RSMaterialComponent.RSTableMetroCustom();
        jPanel1 = new javax.swing.JPanel();
        jbActualizar = new newscomponents.RSButtonFlat_new();
        jcbNombre = new RSMaterialComponent.RSComboBoxMaterial();

        setPreferredSize(new java.awt.Dimension(1466, 839));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setPreferredSize(new java.awt.Dimension(1466, 120));

        jLabel5.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 50)); // NOI18N
        jLabel5.setText("Proveedores");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets.Title/ProvedoresR.png"))); // NOI18N

        jbNuevoProvedor.setBackground(new java.awt.Color(14, 21, 30));
        jbNuevoProvedor.setForeground(new java.awt.Color(255, 255, 255));
        jbNuevoProvedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets.Icons/add.png"))); // NOI18N
        jbNuevoProvedor.setText("Nuevo Proveedor");
        jbNuevoProvedor.setColorMaterial(new java.awt.Color(46, 182, 125));
        jbNuevoProvedor.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 16)); // NOI18N
        jbNuevoProvedor.setIconTextGap(3);
        jbNuevoProvedor.setPreferredSize(new java.awt.Dimension(175, 35));
        jbNuevoProvedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoProvedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 820, Short.MAX_VALUE)
                .addComponent(jbNuevoProvedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(TituloLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jbNuevoProvedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        addMenu.setBackground(new java.awt.Color(46, 182, 125));
        addMenu.setPreferredSize(new java.awt.Dimension(300, 680));
        addMenu.setLayout(new javax.swing.BoxLayout(addMenu, javax.swing.BoxLayout.LINE_AXIS));

        jlBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets.backgrounds/Provedores.png"))); // NOI18N
        jlBackground.setPreferredSize(new java.awt.Dimension(300, 680));
        addMenu.add(jlBackground);

        add(addMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1146, 140, -1, -1));

        Registro.setBackground(new java.awt.Color(255, 255, 255));
        Registro.setPreferredSize(new java.awt.Dimension(1096, 680));
        Registro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jtProvedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Dirección", "Telefono", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtProvedores.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jtProvedores.setBackgoundHead(new java.awt.Color(255, 255, 255));
        jtProvedores.setBorderRows(null);
        jtProvedores.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        jtProvedores.setColorSecondary(new java.awt.Color(255, 255, 255));
        jtProvedores.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        jtProvedores.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jtProvedores.setFontHead(new java.awt.Font("Metropolis Semi Bold", 0, 14)); // NOI18N
        jtProvedores.setFontRowHover(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jtProvedores.setFontRowSelect(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jtProvedores.setForegroundHead(new java.awt.Color(0, 0, 0));
        jtProvedores.setForegroundHover(new java.awt.Color(0, 0, 0));
        jtProvedores.setGridColor(new java.awt.Color(214, 214, 214));
        jtProvedores.setHighHead(25);
        jtProvedores.setPreferredSize(new java.awt.Dimension(1096, 671));
        jtProvedores.setRowHeight(40);
        jtProvedores.setSelectionBackground(new java.awt.Color(46, 182, 125));
        jtProvedores.setShowGrid(false);
        jtProvedores.setShowHorizontalLines(true);
        jtProvedores.getTableHeader().setResizingAllowed(false);
        jtProvedores.getTableHeader().setReorderingAllowed(false);
        jtProvedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProvedoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtProvedores);

        Registro.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1096, 650));

        jPanel1.setBackground(new java.awt.Color(14, 21, 30));
        jPanel1.setPreferredSize(new java.awt.Dimension(1095, 30));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbActualizar.setBackground(new java.awt.Color(14, 21, 30));
        jbActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets.Icons/actualizar.png"))); // NOI18N
        jbActualizar.setText("Actualizar");
        jbActualizar.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 14)); // NOI18N
        jbActualizar.setPreferredSize(new java.awt.Dimension(120, 30));
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jbActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 0, -1, -1));

        jcbNombre.setBackground(new java.awt.Color(14, 21, 30));
        jcbNombre.setForeground(new java.awt.Color(255, 255, 255));
        jcbNombre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Filtrar por Nombre" }));
        jcbNombre.setColorMaterial(new java.awt.Color(46, 182, 125));
        jcbNombre.setEnabled(false);
        jcbNombre.setFont(new java.awt.Font("Metropolis Semi Bold", 0, 14)); // NOI18N
        jcbNombre.setPreferredSize(new java.awt.Dimension(200, 30));
        jcbNombre.setThemeTooltip(necesario.Global.THEMETOOLTIP.LIGHT);
        jPanel1.add(jcbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        Registro.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jbNuevoProvedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoProvedorActionPerformed
       new CambiaPanel(this.addMenu, new nuevoProvedor());
    }//GEN-LAST:event_jbNuevoProvedorActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
         try{
            Conexion con = new Conexion("jdbc:mysql://localhost:3306/e-wod","root","");
            Provedor_data provedor_data = new Provedor_data(con);
            List<Provedor> lista_provedores = provedor_data.obtenerProvedores();
            
            mostrarLista(lista_provedores);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "No se pudo cargar la tabla ");
        }
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jtProvedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProvedoresMouseClicked
        int fila = this.jtProvedores.getSelectedRow();

        nombre = jtProvedores.getValueAt(fila, 0).toString();
        direccion = jtProvedores.getValueAt(fila, 1).toString();
        telefono = jtProvedores.getValueAt(fila, 2).toString();
        correo = jtProvedores.getValueAt(fila, 3).toString();
        try{
            Conexion con = new Conexion("jdbc:mysql://localhost:3306/e-wod","root","");
            Provedor_data provedor_data = new Provedor_data(con);

            provedor_pasado = provedor_data.getProvedor_por_nombre(nombre);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "No se pudo cargar el detalle, intente otra vez  ");
        }
        new CambiaPanel(this.addMenu, new detalleProvedor());
    }//GEN-LAST:event_jtProvedoresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Registro;
    private javax.swing.JPanel Titulo;
    public static javax.swing.JPanel addMenu;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private newscomponents.RSButtonFlat_new jbActualizar;
    private rsbuttoncustom.RSButtonCustom jbNuevoProvedor;
    private RSMaterialComponent.RSComboBoxMaterial jcbNombre;
    public static javax.swing.JLabel jlBackground;
    private RSMaterialComponent.RSTableMetroCustom jtProvedores;
    // End of variables declaration//GEN-END:variables
}
